### ISSUE TITLE
Error when pressing the markdown-button

### ISSUE THREAD

**Issue by CarlssonLeo** [natfarleydev/anki-auto-markdown#11]
Hi! 

Just found your addon, and tried it in the purpose of helping me memorise sql and javascript. However, it does not seem to work currently. Whenever I press the Markdown-button, I get the following error: 

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.41 (312fa278) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-04-03 21:19:27
Add-ons possibly involved: ⁨Auto Markdown - fix version⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 526, in handler
  File "/Users/leocarlsson/Library/Application Support/Anki2/addons21/15061497/editor.py", line 137, in onHtmlAvailable
    edited_field_html = re.sub(r'<img src="(.*?)".*?>', r'![An image](\1)', field_html)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/re.py", line 210, in sub
    def subn(pattern, repl, string, count=0, flags=0):
TypeError: expected string or bytes-like object
```

**Comment by natfarleydev** [comment]
Hi @CarlssonLeo, looks like this is a bug due to the changes in the editor, thanks for reporting. (There are significant changes to the way Anki's editor code works in 2.1.41+)

I don't have much time to look into this at the moment, but if you have a choice, I run 2.1.40 without issues. 

I'll see if I can have a look in the near future, but if anyone else wants a go at fixing this, PRs are welcome!

**Comment by natfarleydev** [comment]
Hi @CarlssonLeo , can you check with the latest release? This has been fixed for me now

**Comment by CarlssonLeo** [comment]
Thank you @natfarleydev ! Did some simple tests, and yes! It seems to work :)
