### ISSUE TITLE
'NoneType' object has no attribute 'strip' / TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by ben-hampson** [natfarleydev/anki-auto-markdown#13]
I typed in `*test*` into my 'Basic' card which has 'Convert to/from markdown' switched on for the front field. On switching to the back field, this error occurs. I also get it even if I don't use markdown. (input: `test`)

```
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-14 14:37:00
Add-ons possibly involved: ⁨Auto Markdown - fix version⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 526, in handler
  File "/Users/bhampson/Library/Application Support/Anki2/addons21/15061497/editor.py", line 223, in onInnerTextAvailable
    updated_field_html = generateHtmlFromMarkdown(field_text, field_html)
  File "/Users/bhampson/Library/Application Support/Anki2/addons21/15061497/editor.py", line 28, in generateHtmlFromMarkdown
    generated_html = markdown.markdown(field_plain, extensions=[
  File "/Users/bhampson/Library/Application Support/Anki2/addons21/15061497/markdown/__init__.py", line 494, in markdown
    return md.convert(text)
  File "/Users/bhampson/Library/Application Support/Anki2/addons21/15061497/markdown/__init__.py", line 355, in convert
    if not source.strip():
AttributeError: 'NoneType' object has no attribute 'strip'
```

If I click on the Markdown button instead I get this following error. Again, it's the same if I just input `test`:

```
Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 526, in handler
  File "/Users/bhampson/Library/Application Support/Anki2/addons21/15061497/editor.py", line 137, in onHtmlAvailable
    edited_field_html = re.sub(r'<img src="(.*?)".*?>', r'![An image](\1)', field_html)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

**Comment by ribber** [comment]
I meet this bug too

**Comment by natfarleydev** [comment]
Thanks @Ben-Hampson and @ribber, can you check the latest version of the plugin on Ankiweb? This should fix the issue 🤞

**Comment by ribber** [comment]
Thank you very much @natfarleydev
