### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'model'

### ISSUE THREAD

**Issue by anibal-aguila** [natfarleydev/anki-auto-markdown#2]
Hi I get this error on Filds.. button

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-02 20:41:54
Add-ons possibly involved: ?Auto Markdown - fix version?

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 493, in handler
  File "aqt/editor.py", line 481, in <lambda>
  File "aqt/editor.py", line 352, in _onFields
  File "/home/userx/.local/share/Anki2/addons21/15061497/fields.py", line 18, in fieldDialog__init__
    self.model = note.model()
AttributeError: 'dict' object has no attribute 'model'
```

**Comment by natfarleydev** [comment]
Thanks for your issue @anibal-aguila, this should now be fixed in `master`, and I'm hoping to upload to AnkiWeb sometime today.

**Comment by anibal-aguila** [comment]
Hi @natfarleydev, after the update the add-on I can see the anki fields options but get the following error:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-05 10:49:07
Add-ons possibly involved: ⁨Auto Markdown - fix version⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/fields.py", line 205, in accept
  File "</usr/local/share/anki/bin/decorator.pyc:decorator-gen-2>", line 2, in saveField
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 630, in repl
  File "/home/userx/.local/share/Anki2/addons21/15061497/__init__.py", line 44, in FieldDialog__saveField__new
    if fld["perform-auto-markdown"] != perform_auto_markdown:
KeyError: 'perform-auto-markdown'

```

![image](https://user-images.githubusercontent.com/49025536/92304627-f9db3800-ef7f-11ea-8212-48319d647f7b.png)

**Comment by natfarleydev** [comment]
I'll take another look; I'm fairly sure I know how to fix this so it should be fixed and up on AnkiWeb by sometime tomorrow

**Comment by natfarleydev** [comment]
@anibal-aguila Could you try the version on AnkiWeb now?

**Comment by anibal-aguila** [comment]
@natfarleydev it's working
thanks :+1:
